name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy site
        run: npm run build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.3.0
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './_site'
          DEPLOY_DIR: '/blog'
          CLEANUP: 'True'
          NEKOWEB_PAGENAME: 'Karhukarhu'
